#!/bin/bash

set -e
echo "Running Min-Time OTM Experiment 1"

for i in 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100
do
    for j in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
    do 
    	for l in 0 1 2 3 4 5 6 7 8 9
    	do
		    echo "Running fast algorithm on plot_${i}_$j"
		    echo "Fast on plot_${i}_$j" >> Experiment2/run_output.txt
		    ../build/min-lat "Experiment2/plot_${i}_$j.txt" 4 2 >> Experiment2/run_output.txt &
		    ../build/multi-otm 2 1 "Test_Set_01/plot_${i}_$j.txt" 1 > Test_Set_01/run_output.txt &
		    wait
        done
    done
done


for i in 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100
do
    for j in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
    do 
	    echo "Running MILP algorithm on plot_${i}_$j"
	    echo "MILP on plot_${i}_$j" >> Experiment2/run_output.txt
	    ../build/min-lat "Experiment2/plot_${i}_$j.txt" 4 2 >> Experiment2/run_output.txt &
	    ../build/multi-otm 2 1 "Test_Set_01/plot_${i}_$j.txt" 1 > Test_Set_01/run_output.txt &
	    wait
    done
done

